export const detalii = {
    moldoveanu: {
        titlu: "VARFUL MOLDOVEANU",
        descriere: [
            "Vârful Moldoveanu este cel mai înalt vârf montan din România, cunoscut și sub numele de Acoperișul României, având o altitudine de 2.544 m, fiind vizibil doar de pe minunata Creastă a Făgărașului sau din aer. Acesta se află în mijlocul Munților Făgăraș, oferind acestora împreună cu alte nouă vârfuri semețe, o unicitate aparte. Emoțiile și sentimentele de bucurie și împlinire când ajungi în vârf, ținând în mână steagul țării, sunt greu de exprimat în cuvinte. Este practic o victorie personală să ajungi pe Vârful Moldoveanu!",
            "Există trei trasee principale care duc către faimosul Moldoveanu, toate ne trec prin peisaje complexe, de vis, ce necesită o condiție fizică bună și un echipament adecvat perioadei de vizitare. Iarna este foarte dificil de ajuns aici, deoarece pericolul de avalanșe este ridicat, doar cei experimentați își exersează cățărările cu echipamente speciale. Una dintre variante este parcurgerea drumeției prin Valea Rea, cunoscut ca fiind cel mai ușor drum către destinație, ce poate fi parcurs într-o singură zi, dacă nu optați pentru campare. Marcajele care se urmează sunt Stâna din Valea Rea- Căldarea Văii Rele- Iezerul Triunghiular- Portița Viștei- Vârful Viștea Mare- Vârful Moldoveanu.",
            "De-a lungul acestei rute puteți admira Cascada Mare a Văii Rele, Iezerul Triunghiular..."
        ],
        descriere2: [
            "O altă opțiune este parcurgerea drumeției prin Valea Vâlsanului, pentru care trebuie să aveți la dispoziție două zile de aventură, deoarece lungimea rutei este de 35 km ce se parcurg cam în 12-16 ore de mers. Acest lucru implică și campare în zonele special amenajate de pe traseu, echiparea suplimentară cu un cort, un sac de dormit și mai multe provizii de hrană.",
            "Acest traseu ne oferă posibilitatea de a petrece o noapte liniștită în mijlocul naturii, departe de aglomerația urbană, de rutina cotidiană; putem să ne relaxăm și să ne revigorăm într-un loc frumos, cu un peisaj mirific. Marcajele care se urmăresc sunt Barajul Vâlsan- Vârful Galbena- Lacul Galbena- Vârful Roșu- Vârful Moldoveanu. Totul începe admirând lacul și barajul Vâlsanului, apoi se continuă pe un drum forestier ce duce de la Brădet pe aceeași vale, se ajunge pe Muchia muntelui Tuica, pe Șaua Scărișoara, în minunata zonă Galbena (cea mai impresionantă priveliște), după care se escaladează Vârful Roșu pentru a ajunge la destinație.",
            "Este nevoie de o condiție fizică foarte bună, de răbdare, de multă ambiție, fiind un traseu lung, cu multe zone abrupte, înalte, stâncoase și umede; purtarea unui echipament complet expedițiilor montane este obligatorie. O ultimă alternativă este începerea rutei de la Bâlea Lac, fiind considerat cel mai dificil traseu. Și în acest caz aveți nevoie de două zile pentru a parcurge dus- întors ruta, undeva la nouă ore pe zi se estimează escaladarea. Pentru înnoptare puteți alege variante de campare în zonele amenajate sau să vă cazați la Cabana Podragu.",
            "De-a lungul drumeției vom admira zona Bâlea Lac (neapărat trebuie să vizităm Hotelul de Gheață), apoi continuăm cu Șaua Capra, respectiv frumosul Lac Capra (aici putem admira caprele negre), ajungem la Portița Arpașului, după care traversăm o zonă foarte dificilă numită La trei pași de moarte. Dacă am trecut cu bine și mai avem forță, continuăm cu Șaua Vârtopului, Arpașul Mare, Iezerul Podul Giurgiului (aici regăsim și un refugiu), Șaua Podragului, Șaua Ucei Mari, Șaua Orzanelor, traversăm Vârful Viștea Mare și ajungem la Vârful Moldoveanu.",
            "Este un traseu greu, dar peisajele complexe cu lacuri, cascade, păduri, pajiști multicolore, stânci abrupte și o faună minunată, merită tot efortul, în final obținem o victorie, o bucurie și o emoție de intensitate maximă.",
            "Sfarsit de zi perfecta 😊 Stana lui Burnei 1300 m."
        ]
    },

   negoiu: {
    titlu: "VARFUL NEGOIU",
    titlu2: "OTHER TRIPS",
    descriere: [
        "Vârful Negoiu este un vârf montan situat în Masivul Făgăraș, județul Sibiu. Cu o altitudine de 2.535 metri, Negoiu este al doilea ca înălțime în România, fiind devansat doar de Vârful Moldoveanu, altitudine 2.544 de metri. Până în perioada interbelică era considerat cel mai înalt vârf din Carpați, exceptând Masivul Tatra. Este cunoscut drept fiind polul instabilității atmosferice din România.",
        "Pentru a ajunge pe acest varf exista multe trasee pe care fiecare dintre noi le putem combina, in functie de puterea si disponibilitatea fizica, de dorinta, de timpul avut la dispozitie, cu plecare de la Cabana Negoiu, de la Lacul Balea, Piscul Negru si poate si de altundeva. Sunt convinsa, ca oricare varianta de poteca am alege am fi rasplatiti cu peisaje minunate. Pentru ca imensitatea crestelor dantelate din Fagaras parca nicaieri nu se vad asa de frumos, lacul Caltun este printre cele mai frumoase lacuri glaciare si cascada Saratii care se revarsa de sus din Custura Saratii si formeaza raul care curge la vale creeaza un spectacol minunat care iti da fiori. Noi am plecat de 2 3 ori de la Balea Lac si o data de la cabana Negoiu. Toate variantele alese de noi au fost niste ture solicitante de dificultate medie (spre grea), fiecare dintre ele ne-au luat vreo 10-11-12 ore.",
    ],
    descriere2: [
        "În cazul în care vrem să revedem frumusețile de pe Transfăgărășan și să pornim în expediție de la Lacul Bâlea, în funcție de perioada aleasă putem vizita Cetatea Poienari, Barajul Vidraru (aici putem face bungee jumping, plimbări cu barca și să participăm la diverse competiții de înot, ciclism sau raliu), Cascada Capra și zona Bâlea (neapărat trebuie să vizităm Hotelul de Gheață, unicul din Europa de Est, să ne plimbăm cu telecabina și să practicăm sporturi de iarnă- schi, săniuș). Zona Bâlea ne înfrumusețează privirile cu peisaje de iarnă chiar și vara, fiind un loc răcoros, care duce către cel mai impresionant vârf, Vârful Negoiu.",
        "Cele două rute montane cele mai utilizate de către iubitorii de munte sunt Lacul Bâlea- Vârful Lăițel- Lacul Călțun- Strunga Doamnei- Vârful Negoiu sau Cabana Negoiu- Piatra Prânzului- Șaua Cleopatrei- Vârful Negoiu. Indiferent de opțiunea aleasă peisajele surprinse sunt de vis, merită orice efort, cu siguranță vom reveni în aceste locuri unicate. Ambele trasee au de-a lungul lor zone pentru popas (Piatra Prânzului sau Lacul Călțun), izvoare de apă pentru realimentare, porțiuni cu serpentine, alunecoase, stâncoase, abrupte, dar și zone cu pajiști multicolore, păduri dese și arbuști fructiferi.",
    ],
   },
   omu: {
    titlu: "VARFUL OMU",
    titluBabele: "Babele - Monument natural",
    descriere: [
        "Dacă nu ai urcat niciodată pe vârful Omu și ai un nivel de începător ai nimerit în locul potrivit. În acest articol vei găsi toate detaliile de care ai nevoie pentru a-ți organiza acest traseu. Îmi doream de foarte mult timp să urc pe Vârful Omu, dar de fiecare dată vremea ne-a stricat planurile. De data aceasta nu a fost ceva organizat, era vineri seară și căutam activități de weekend. Dintr-o glumă ne-a venit ideea să urcăm pe Vârful Omu, prognoza meteo anunța soare toată ziua, vânt slab și fără șanse de precipitații.",
        "Fără să mai stăm pe gânduri am pregătit repede rucsacul de treking și echipamentul de drumeție și am început să căutăm variante de trasee. Drumul este într-o stare extrem de bună, doar ultima porțiune nu este asfaltată, dar se poate parcurge cu o mașină normală sau poți parca chiar unde se termină asfaltul. Dacă vrei să scurtezi și tu traseul, atunci trebuie să ajungi cu mașina aici. O altă variantă pentru acest traseu ar mai fi să urci cu telecabina până la Babele și mai scutești încă 1 oră de mers/sens. În acest caz poți veni și cu trenul până la Bușteni și de acolo iei telecabina. ",
    ],
    descriere2: [
        "Masivul Bucegi este o cetate naturală prin complexitatea structurală și morfologică, cu vârfuri care depășesc 2500 de metri, abrupturi aproape verticale, masivitate și priveliști de o diversitate fără egal.",
        "Vârful Omu, locul care ne-a făcut alpiniști pe toți, pentru că nu-i român care să nu fi calcat măcar o dată în jurul Sfinxului și al Babelor, are o înălțime incertă. Nu pentru că lucrează pitici din măruntaile pământului, ci pentru că modul de măsurare este diferit pentru unii și pentru alții.",
        "Oficial Vârful Omu are 2.505 metri și este cel mai înalt vârf din Munții Bucegi. Există însă unii care socotesc și înălțimea bolovanului din vârf ceea ce ar duce înălțimea vârfului la 2.514 metri. Diferența nu pare foarte mare, dar cei câțiva metri în plus, în clasamentul celor mai înalte vârfuri din România, ar muta Vârful Omu de pe locul 11, cel oficial, pe locul șase.",
        "Primul tronson din traseul spre vârful Omu se întinde la Piatra Arsă până la Camana Babele. Acest traseu este recomandat tuturor, dar mai ales copiilor de toate vârstele, dar și celor care vor să se inițieze în drumeții montane.",
        "Din spatele cabanei Piatra Arsă, 1950 m, trebuie să intri în curtea complexului caută marcajul bandă galbenă, care urcă uşor de-a lungul Platoului Jepilor Mari. După circa 15 min de la cabană, vei ajunge la o răscruce de drumuri, ține marcajul bandă galbenă.",
    ],
    descriere3: [
        "De la bifurcaţia de mai sus, urmăm la stânga, drumul de căruţă, ieşind curând pe coama Babele-Jepi. Va urma o urcare continuă, dar lejeră, care ne conduce la cabana Babele (2200 m). În imediata vecinătate a cabanei se află probabil cele mai vizitate obiective turistice din România: Babele și Sfinxul. Aici vom face prima pauză de masă și vom sta să admirăm aceste frumuseți și minunății naturale",
    ],
    descriere4: [
        "Înfăţişarea aparte de babe se datorează zonei de munte, care este alcătuită din calcar și gresie, ce a fost roasă de intemperii și trecerea timpului. Oamenii de ştiință spun că apa, vântul, dar și înghețul și  dezgheţul au creat aceste două stânci care seamănă cu nişte babe cocoşate ce stau la şuetă.",
        "Există, desigur, şi multe poveşti privind originea Babelor. Formele lor ciudate au dat naștere legendelor, care spun că acestea au avut rol de sanctuare dacice unde se aduceau jertfe zeilor. Desigur că legendele spun multe, dar un lucru este cert: frumuseţea rară a acestor monumente naturale.",
        "Monumentul Babele a fost numit și „Altarele ciclopice din Caraiman”, fiind  consacrate Pământului şi Cerului, Soarelui şi Lunii, datorită apropierii lor de un alt monument natural – Sfinxul, care le păzeşte.  Chiar dacă am accepta că Babele sunt stranii chipuri de piatră ce stau la barfă lângă Sfinx, sunt doar creaţia naturii și nu opera unor îndepărtați strămoși. Nu se ştie dacă au fost așa mereu ori omul a intervenit asupra lor, dându-le forma de azi."
    ]
   },
   about: {
    titlu: "Impresii si pareri",
    descriere: [
        "Cu oamenii dragi de la CMA (Clubul Montan Apuseni) mai fusesem pe trasee si stiam ca orice excursie cu ei va fi un deliciu. O delectare vizuala si sociala. Un fel de team building cu necunoscuti, dar care te va invata multe despre ceea ce inseamna muntele, tainele copacilor, enigma fiecarui izvor si lectiile date propriului corp.",
        "Multumesc organizatorilor Dan, Cosmina si Liviu pentru ca au facut posibila aceasta minunata evadare in natura a 100 de persoane. Ne-am bucurat alaturi de voi, de abudenta de narcise salbatice, de peisaje fara concurenta,de prospetime si culoare, de oameni frumosi si veseli, ozonandu-ne plamanii, acolo sus de tot, pe sub bogata cetina de brad cu cel mai pur aer. Nimic nu a sunat a comercial ci totul, dar absolut totul s-a consumat cu multa daruire , de la suflet la suflet. Felicitari dragii mei .",
    ],
    descriere2: [
        "Pentru mine, excursia câștigată a reprezentat o modalitate de cunoaștere și de autocunoaștere. Mi-a plăcut faptul că ați fost flexibili, dar și atenți la respectarea programului ( și a nevoilor tuturor participanților). De asemenea, am rămas plăcut impresionată de grupul variat interesat de munte (atât din punctul de vedere al locațiilor- mă refer la cei care au venit din alte orașe -ex. Timișoara, cât și al diversitatății vârstelor- tineri și vârstnici).",
        "Am stat si m-am gandit, nu prea mult si mi-am spus: daca toata vara am petrecut-o impreuna si ne-ai aratat cat de frumoasa poate fi tara noastra si cat de frumosi pot deveni oamenii in mijlocul naturii ; ar fi pacat sa nu incheiem impreuna si anul. Mai mult,  povestile si pozele postate imi aduc acasa si pe fiica mea, deci? te rog sa ma inscrii cu doua persoane pentru revelion."
    ]
   },
   team: {
    titluTeam: 'Ce ACTIVITATI VERZI poti incerca cu ECHIPA NOASTRA',
    titlu: 'Echipa Green Adventure are urmatoarele certificari:',
    descriere: [
        'RAFTING, PowerRafting si SuperRafting, CAIAC, CANYONING, DRUMETII, WHITE WATER si Programe de VACANTE EXTERNE.  Pe scurt, avem orice si-ar putea dori un aventurier dornic sa scape din jungla citadina si sa respire aer curat si natura, sa echilibreze zilele interminabile de la birou, cu mici „potiuni magice de fericire”.  Cand dorinta de NOU se strecoara in ganduri si te cheama afara la joaca, noi, cei din echipa GREEN ADVENTURE, suntem prezenti sa-ti oferim exact ce ai nevoie, in conditii de maxima siguranta!'
    ],
    certificari: ['World Rafting Federation (WRF): certificare internationala de instructor de rafting national clasa 2, 3 si 4.',
    "International Rafting Federation (IRF): certificare internationala ghid de rafting clasa 3",
    "British Canoe Sea & White Water Kayak: certificare internationala ghid de caiac in conditii de flat water  si     rauri montane",
    "International Canyoning Organization For Professionals (IcoPro): certificare internationala ghid de canyoning.",
    'British Canoe White Water Rescue & Safety: certificare internationala pentru salvatori slavatori din rauri de munte.',
    "Ghid montan: certificare nationala pentru activitatile montane.",
    'Ghid local si national: certificare nationala pentru activitati de turism national si international.'
]
   },
   apuseni: {
    titlu: 'Muntii Apuseni',
    idei: ' Ce sa vizitezi in Apuseni',
    descriere: [
        "Unul dintre cele mai surprinzătoare trasee pe care le-am făcut în România este Circuitul Scărița Belioara. Rezervația geo-botanică Scărița Belioara face parte din masivul Muntele Mare și se află pe teritoriul administrativ al comunelor Poșaga și Ocoliș din județul Alba.",
        'Ca să ajungi aici nu e foarte dificil.',
        'De pe DN 75 (Valea Arieșului, Câmpeni – Turda) ia-o spre Poșaga de Sus, pe un drum parțial asfaltat, care apoi se transformă în drum de pământ, dar de bună calitate. Traseul pornește pe un drum forestier spre stânga, iar după câteva sute de metri urcă abrupt pe o pajiște având în spatele nostru impunătorul abrupt Șesul Craiului 🙂',
    ],
    descriere2: [
        "Apoi urmează prima parte mai tehnică a acestui circuit: o urcare pe stânci destul de abruptă, însă fără a fi nevoie de tehnici de cățărare. Această porțiune este foarte scurtă, sub 200 m. Apoi se intră în pădure până când se iese într-o poiană mare în care se află câteva case răsfirate și părăsite cu acoperiș din paie.",
        "După aprox. 2 ore de la pornire ieșim din pădure în golul alpin la altitudinea de 1300 m. Aici întâlnim o nouă intersecție unde noi urmăm traseul circuitului spre dreapta, în urcare. Spre stânga există un traseu care ajunge în stațiunea Muntele Băișorii. Urmăm drumul înierbat spre dreapta și, după o urcare destul de scurtă și ușoară, vedem în sfârșit celebrul peisaj din Scărița – Belioara.",
        "Suntem sus în Șesul Craiului cu abruptul stâncos sub noi care creează prăpăstii amețitoare de sute de metri adâncime! Există chiar și o potecă tematică aici sus, marcată prin panouri cu explicații și imagini despre fauna și flora întâlnită în această rezervație. "
    ],
    descriere3: [
        "Odată ajunși în zona centrală a abruptului stâncos puteți înainta până pe cea mai extremă stâncă de unde puteți admira întreaga vale a coumnei Poșaga și Munții Trascău în depărtare. Este o imagine cu adevărat spectaculoasă și am fost surprinși să vedem atâta frumusețe într-un loc nu tare popular.",
        "Ne continuăm traseul pe marginea abruptului, iar uneori poteca trece fix pe marginea prăpastiei așa că în câteva locuri ar fi bine să nu te uiți în jos dacă ai rău de înălțime 😛. Piesajele spre Sud – Est sunt foarte pitorești: stânci, văi, munți verzi plini de păduri, pajiști. Un peisaj pitoresc tipic zonelor montane mai joase ale Carpaților.",
        "Din acest punct intrăm din nou în pădure timp de 15 minute după care ieșim într-o poiană de unde putem vedea foarte bine Coșul Boului. Coșul Boului este o grotă de dimensiuni impresionante, portalul de intrare având aprox. 60 m înălțime.",
        "Nu există potecă marcată pentru a ajunge la acest fenomen carstic, dar există o potecă parțial vizibilă care urcă pieptiș și razant către acest obiectiv. Oricum se vede foarte frumos și de la distanță 🙂",
    ],
    descriere4: [
        "Din această poiană, se continuă coborârea nu foarte accentuată prin pădure și apoi pe albia secată a unui pârâu. Albia e plină de pietre mai mari sau mai mici care fac înaintarea un pic dificilă, existând chiar riscul de a călca greșit. Nouă ne-a plăcut așa de mult această zonă încât cu siguranță vom reveni și vom explora alte câteva obiective în special din zona Ocoliș 🙂"
    ]
   },

   lespezi: {
    titlu: 'VARFUL LESPEZI',
    descriere: [
        'Munții Făgăraș sunt, cu siguranță, cei mai impresionanți munți din România. Compus din şisturi cristaline, masivul Făgăraş se remarcă în ţara noastră prin frumuseţea peisajului şi prin cele şapte vârfuri de peste 2500 de metri altitudine. ',
        'Vârful Lespezi din Munții Făgăraș, cu cei 2517 metri înălțime, este al cincilea vârf din Carpații Românești, după Moldoveanu (2544 m), Negoiu (2535 m), Viștea Mare (2527 m) și Parângul Mare (2519 m). Dintre cele șapte vârfuri din masivul Făgăraș, trei se găsesc grupate în jumătatea vestică a crestei: Negoiu - Lespezi - Cornul Călțunului. Cele trei vârfuri se înșiră pe o lungime a crestei mai mică de 1,5 km.',
        'Situat în partea central vestică a crestei principale, vârful Lespezi este cel mai ușor accesibil de la Complexul Turistic Piscul Negru (1200 m altitudine) aflat pe Transfăgărășan. Cei peste 1300 de metri diferență de nivel se parcurg cu o urcare constantă, fără locuri în care traseul să fie mai domol. Așadar, atenție, este nevoie de o condiție fizică medie spre bună, pentru a putea parcurge traseul și pentru a vă putea întoarce la timp și în siguranță!',
        'Odată ajuns în parcarea complexului, poteca se afundă în pădure, trece de fostele mine și de Peșterile de la Piscul Negru, iar până la primul punct de oprire, Stâna Lespezi, urcușul susținut nu te slăbește deloc. La ieșirea din pădure în golul alpin se poate admira mărețul vârf. De la stână sunt două direcții de ajuns pe vârful Lespezi, una prin stânga care coboară prin vale și iese în Șeuța Lespezi, cealaltă direcție urcă pe Piciorul Lespezi până la vârf. Cu cât urci pe Piciorul Lespezi, începe să se arate fascinanta creastă a Făgărașului și rând pe rând semețele vârfuri.',
        'De pe Vârful Lespezi, poate fi admirată, în toată splendoarea, creasta Făgărașului, cu vârfurile Cornul Călțunului (2510 m), Negoiu (2535 m), Laița (2397 m), Lăițel (2390 m), Vânătarea lui Buteanu (2507 m), Capra (2494 m), Arpașul Mare (2468 m), Buda (2431 m), Viștea Mare (2527 m), Moldoveanu (2544 m), precum și Lacul Călțun și Refugiul Călțun situate la baza vârfului Lespezi.',
        'Atenție! Iarna în Munții Făgăraș este foarte aspră, riscul de avalanșă fiind unul extrem extrem de mare, încă de la primele căderi de zăpadă. Astfel, accesul este recomandat doar alpiniștilor sau turiștilor antrenați, care dețin echipament complet de iarnă, și doar atunci când condițiile meteo și starea zăpezii sunt optime pentru ascensiune.',
    ],
   },
   buila: {
    titlu: "Munții Buila-Vânturarița – Traseu circuit de o zi",
    titlu2: 'Schitul Pahomie – Șaua Ștevioara – Vf. Buila – Curmătura Builei – Schitul Pătrunsa – Schitul Pahomie',
    descriere:[
        "Cel mai nou parc național din România este și unul dintre cele mai sălbatice și frumoase locuri din țara noastră. Munții Buila-Vânturarița nu sunt nici cei mai înalți, nici cei mai întinși, dar te suprind prin peisajele lor spectaculoase. Am ajuns zilele trecute aici și am parcurs un traseu de 20 de kilometri, care ne-a adus în unele dintre cele mai frumoase zone ale masivului. Buila-Vânturarița seamănă pe alocuri cu Ceahlăul, datorită pădurilor dense care înconjoară muntele. Partea estică a masivului imită porțiuni din Piatra-Craiului, iar creasta mai domolă din vest îți dă impresia că ești în anumite locuri din Bucegi.",
        "Vei remarca pe parcursul acestui articol entuziasmul cu care vorbim despre Buila-Vânturarița. El e datorat în întregime bucuriei de a descoperi un masiv în care urmele prezenței umane sunt aproape inexistente și în care echilibrul naturii pare a nu fi perturbat deloc.",
        "Traseul parcurs de noi e unul destul de lung și solicitant, ține cont de acest lucru înainte să porniți la drum. Frumusețea zonelor pe care le traversează compensează însă orice efort și vei vedea asta în imaginile de mai jos. Să pornim, așadar, într-o nouă călătorie #DeasupraMuntilorRomaniei!",
    ],
    descriere2: [
        "Marcaj: Punct albastru până în Șaua Ștevioara; bandă roșie până în Curmătura Builei; cruce albastră până aproape de Schitul Pătrunsa, continuare pe punct galben spre schit; cruce roșie până la Schitul Pahomie / Distanță (dus-întors): 20 km / Timp de mers(dus-întors): 7 ore și 30 de minute / Descarcă de aici harta Parcului Național Buila-Vânturarița",
        'Accesul până la Schitul Pahomie se poate face cu mașina, mergând pe DJ654 din satul Valea Cheii. 10 kilometri din acest drum sunt neasfaltați, însă pot fi parcurși cu orice mașină, cu puțin mai multă atenție pe anumite porțiuni. Verifică prognoza meteo din periaoda în care vrei să mergi, dacă a plouat zdravăn sau a nins înainte, posibil să fie necesară o mașină 4 x 4 pentru aceleași porțiuni mai dificile. Altfel, în condiții obișnuite, nu ai de ce să îți faci griji. Mașina o poți parca lângă Schitul Pahomie, iar de acolo începi traseul pe jos.',
    ],
    descriere3: [
        'Pentru a intra efectiv pe traseu trebuie să treci de schit și să mai mergi circa 300 de metri. Acesta este punctul de intrare pe traseu. Aici vei găsi și indicatorul pentru traseul pe care îl ai în față. Te anunță că faci 4-5 ore până în Șaua Ștevioara, dar noi am făcut puțin peste 3 ore, cu tot cu câteva mici pauze.',
        'E important de știut că traseul nu este unul ușor, urcă în continuu până în șa și e destul de abrupt pe anumite porțiuni. Marcajul e suficient, ba chiar pe anumite porțiuni e proaspăt făcut. Din cauza vegetației (și a faptului că nu e un traseu foarte străbătut) s-ar putea să nu vezi anumite marcaje, așa că recomandăm o atenție sporită în urmărirea lor. Noi l-am pierdut la un moment dat pe urcare, dar am revenit rapid pe potecă. La fel am pățit și la coborâre, așa cum vei vedea mai târziu. Cu excepția urcărilor mai abrupte, traseul nu are porțiuni expuse sau periculoase. Situația se poate complica în caz de vreme rea, când anumite porțiuni devin extrem de alunecoase. Atenție în permanență la prognoza meteo, atât din ziua urcării, cât și din zilele precedente!',
        'Traseul spre Șaua Ștevioară te poartă prin toate tipurile de vegetație. Începi printr-o pădure deasă de foioase, treci apoi printr-o pădure de conifere, întâlnești spre final jnepenii, iar apoi ieși în creastă. În momentul în care ieși din ultima porțiune de pădure începi să vezi fragmente din creasta munților Buila-Vânturarița. Vârful Vânturarița (1.885m) se va vedea în partea dreaptă. Tot în dreapta se dezvăluie porțiunea și mai sălbatică (și mai puțin străbătută/marcată) munților, cea spre Vf. Vioreanu și Curmătura Oale.Odată ajuns în Șaua Ștevioara vezi și mai bine masivele care înconjoară munții pe care te afli. Vei recunoaște rapid Masivul Parâng și Munții Făgăraș. Dacă atmosfera e curată vei vedea și Masivul Retezat. O priveliște și mai bună vei avea din vârfurile Buila și Vânturarița, care sunt în partea dreaptă și stângă a Șeii Ștevioara.',
        'De aici ai două opțiuni. Poți continua traseul spre Vf. Buila (1.848m), în partea stângă, iar de acolo să cobori spre Curmătura Buila, sau poți face un mic ocol și să urci încă vreo 40 de minute spre Vf. Vânturarița, de unde vei avea o priveliște și mai bună spre partea estică a masivului. Noi am ales prima variantă, ca să mai câștigăm puțin timp, însă la următoarea vizită cu siguranță nu vom rata urcarea spre cel mai înalt vârf al Munților Buila-Vânturarița.',
    ],
    descriere4: [
        'Din Vf. Buila și până în superba zonă Curmătura Builei faci cam 30 de minute. Aici găsești și un refugiu cu același nume – Refugiul Curmătura Builei – și la cât de frumoasă e vederea de jur-împrejur, îți vei dori să zăbovești preț de câteva minute aici. Partea cea mai frumoasă a acestui loc e că oferă un unghi bun pentru privit și răsăritul, și apusul. Dacă plănuiești să cobori în aceeași zi, ai grijă să nu te prindă apusul sus. Vei coborî mult prin pădure, iar lumina naturală îți va fi mai de ajutor decât cea a frontalei.',
        'Poți coborî spre Schitul Pătrunsa prin două variante: punct galben, dar treci printr-o zonă mai abruptă și mai expusă, sau cruce albastră, coborând în mare parte prin pădure, mai lin. „Dezavantajul”, în cea de a doua variantă, e că mai ai de mers încă 10-15 minute în plus până la Schitul Pătrunsa.',
        'Chiar și așa, noi am ales varianta mai lejeră. Din Curmătura Builei la schit am ajuns în o oră și 10 minute. Atât doar că ne-a fost dificil să găsim marcajul potrivit chiar în primele minute după ce am început coborârea de la curmătură. Fie nu l-am văzut din cauza vegetației, fie pur și simplu ne-a scăpat, cert e că am pierdut vreo 15-20 de minute coborând puțin și căutând marcajul.',
        'Odată ajuns la Schitul Pătrunsa începe „operațiunea” de relaxare a picioarelor și de testare a anduranței. Nu mai urci, dar mai ai de mers câțiva kilometri pe potecă și apoi pe drum forestier. Marcajul pe care îl urmeză e cruce roșie, iar între cele două mănăstiri faci aproximativ o oră. Vei avea timp suficient să te gândești la priveliștile minunate care ți-au fost oferite peste zi și să plănuiești o nouă vizită în Buila-Vânturarița. Noi așa am făcut și știm sigur că în această toamnă vom avea o nouă întâlnire cu masivul care ne-a încântat atât de tare.',
    ],
   },

   caltun: {
    titlu: 'LACUL CALTUN',
    descriere: ['Munții Făgăraș nu sunt degeaba numiți Alpii Transilvaniei. Aceștia găzduiesc 8 vârfuri ce măsoară peste 2500 m, dar și numeroase cascade și lacuri glaciare. Aici, unde cerul pare mai aproape ca niciodată, se găsește un lac glaciar de o frumusețe răpitoare: Lacul Călțun.',
    'Traseul pe care l-am ales pentru ziua de 30 august 2014 avea ca punct de plecare Lacul Bâlea, care la ora 10 fără ceva era încă lipsit de forfota caracteristică. Cerul senin, răcoarea plăcută și prognoza meteo favorabilă, mă făceau să îmi doresc să pornim cât mai repede la drum. Până ne-am lămurit de unde începe traseul, până ne-am schimbat, ceasul arăta deja ora 10. Mă așteptam la o zi lungă, speram doar să nu ajungem înapoi pe întuneric. Poteca începea de lângă parcarea de pe partea stângă, cum ieși din tunel, venind dinspre Curtea de Argeș.',
    'Am început urcușul pe Curmătura Bâlii, marcaj cruce roșie, apoi am urmat marcajul bandă albastră spre Șaua Paltinului, unde în sfârșit am facut o pauză de la urcat. Însă faptul că începusem să coborâm destul de serios, mă făcea să mă gândesc cu groază la diferența de nivel pe care trebuia să o recuperăm la un moment dat.',
    ],
    descriere2: [   
        'În curând am întâlnit prima porțiune de cabluri, care nu ne-a pus mari probleme. Pauzele erau din ce în ce mai dese, nu fiindcă obosisem, ci pentru ca nu mă mai săturam să imortalizez peisajul de vis ce ni se arăta. Mă uitam înspre Vârful Lăițel care se zărea în fața noastră și aveam impresia că traseul avea să fie destul de domol. Numai că a urmat și a doua porțiune de cabluri, care leagă practic Vârful Lăița de Vârful Lăițel. Aceasta a fost destul dificilă și abruptă, recomand o atenție sporită. ',
        'De aici până la Vârful Lăițel nu mai era mult, așa că în scurt timp am ajuns la altitudinea de 2390 m. Dar răsplata cea mai mare a fost imaginea Căldării Călțun, unde strălucea ca un diamant în lumina soarelui Lacul Călțun. Am zăbovit aici minute bune, anticipând parcă ce avea să urmeze. Cea mai dificilă porțiune mi s-a parut această bucată de coborâre de pe Lăițel. ',
        'Diferența de nivel nu era mare, în jur de vreo 200 m, însă erau numai roci, care păreau destul de instabile, trebuia să fim foarte atenți la fiecare pas. Recunosc: am coborât mai mult târâș și mă gândeam în continuu dacă noi pe aici va trebui să ne întoarcem??? Cerul deja se acoperea de nori, iar pe măsură ce ne apropiam de Căldarea Călțun curenții de aer erau din ce în ce mai puternici.',
    ],
    descriere3: [
        'Am plecat de la diamantul Făgărașului, nu înainte să aruncăm o privire în spate către Vârful Negoiu (2535 m), cu care ne vom întâlni cu siguranță în viitorul apropiat! Nu pot să spun că drumul de întoarcere a fost ca o plimbare în parc. Porțiunile de jnepeniș asociate cu bolovani ne-au solicitat destul de serios la nivel fizic, dar și psihic. Acum este cel mai important să nu te relaxezi si să rămâi cât se poate de concentrat. Ritmul a fost mult mai domol la întoarcere, tufele de afine pe care le întâlneam erau irezistibile și corpul meu parcă simțea că va avea nevoie de mai multă energie exact la final. De ce spun asta? Uite ce am avut de traversat pentru a ajunge la capătul sudic al tunelului de pe Transfăgărăşan. ',
        'La ora 19:00 am ajuns în Șaua Pisicii, unde eram la propriu cu capul în nori. Vizibilitatea era scazută, însă reuşeam să vedem Transfăgărăsanul, ceea ce ne mai ridica un pic moralul. Drumul mi se părea interminabil, mă uitam cu disperare după tunelul care nu îşi mai făcea odată apariția. La ora 20:15 am intrat în tunel iar la ora 20:30 am ajuns înapoi în parcare, exact când se lăsa noaptea.',
    ]
   },

   capra: {
    descriere: [
        'Frumoasele lacuri ale României alcătuiesc locuri ideale pentru escapade de weekend, zone liniştite tot mai accesate de către turiştii dornici să petreacă momente relaxante în natură. Unul dintre cele mai frumoase lacuri de pe teritoriul ţării noastre se află pe versantul sudic al Masivului Făgăraş, acesta poartă numele de Lacul Capra şi îmbie turiştii să-şi tragă sufletul chiar şi pentru câteva clipe, în mijlocul naturii. ',
        'Apele glaciare se află la altitudinea de 2230 de metri, întreaga zonă oferă o privelişte greu de descris în cuvinte asupra asupra vârfurilor Buda, Raiosu şi Museteica. Apele liniştite se află în apropiere de splendidul Bâlea Lac, de aici ajungi în doar 45 de minute spre Lacul Capra. Lacul glaciar are o adâncime medie de aproximativ 11 metri, ocupă o suprafaţă totală de 1,80 hectare şi are o formă neregulată, aproape rotundă. ',
        'Pentru mulţi dintre noi o vacanţă la munte nu ar mai fi aceeaşi în lipsa unor drumeţii în mijlocul naturii, de aceea trebuie să ştii că lacul este punctul de pornire spre trasee montane deosebite. Un traseu care poate fi urmat de aici este cel care duce spre Vârful lui Buteanu, un drum destul de dificil, dar care merită tot efortul. Vârful măsoară 2507 metri şi oferă privelişti minunate spre Munţii Făgăraş. Poţi coborî mai apoi spre Căldarea Vaiuga, iar de aici nu mai este mult până la Bâlea Lac. Drumul marcat care duce spre Creasta Arpaselului este şi mai dificil, dar la fel de interesant. ',
        'Capra este unul dintre cele mai importante lacuri piscicole aflate la înălţime, iubitorii acestei activităţi pot petrece ore în şir pe malurile apelor, la pescuit. O mulţime de specii de peşti populează apele liniştite, iar amatorii sunt bucuroşi să le captureze în undiţele lor. ',
    ],
    descriere2: [
        'Unul dintre cele mai frumoase lacuri de pe teritoriul ţării noastre se află pe versantul sudic al Masivului Făgăraş, acesta poartă numele de Lacul Capra şi îmbie turiştii să-şi tragă sufletul chiar şi pentru câteva clipe, în mijlocul naturii. ',
        'Lacul Capra este un lac glaciar ascuns în inima Munților Făgăraș,  la o altitudine  de 2230 de metri și are o adâncime maximă de circa 10-11 metri. Din Lacul Capra pleacă pârâul Capra (tributar al râului Argeș), care în doar câțiva metri formează un alt lac mic, Căprița. Mai departe, pârâul coboară spre sud și chiar înainte de Transfăgărășan formează frumoasa Cascadă Capra. Lacul ocupă o suprafaţă totală de 1,80 hectare şi are o formă neregulată, aproape rotundă. ',
        'Pentru cei care vor să viziteze zona Transfăgărășan și Munții Făgăraș, Lacul Capra este un obiectiv turistic care nu trebuie să lipsească de pe lista obiectivelor naturale din zonă. Întreaga zonă oferă o privelişte greu de descris în cuvinte asupra vârfurilor Buda, Râiosu şi Mușeteica. ',
    ]
   },

   parang: {
    descriere: [
        'Pe cuprinsul întinderii munților Parâng se găsesc un vârf muntos de peste 2.500 de metri, și anume vârful Parângul Mare, cu 2.519 m și trei vârfuri de peste 2.400 de metri: Gemănarea, cu 2.426 m, Stoinița, cu 2.421 m și Cârja cu 2.405 m și aproximativ 15 vârfuri de peste 2.300 m.  Masivul Parâng este cel mai tipic nod orografic al Carpaților Românești – dominat de vârful Parângul Mare (2519 m) din care se desprind, divergent lanțurile montane: spre est Munții Căpățânii, spre NE Munții Lotrului (Ștefleștilor), Latoriței și Cindrel, iar spre NV Munții Șureanu. ',
        'Munții Parâng situați în partea sud-vestică, rămân partea cea mai înaltă a grupei. Din culmea principală se desprind o serie de ramificații sudice prelungi și bine împădurite. Astfel, din Vf. Parângu Mare se desprind Vf. Mândra (2360 m) și Moldivișul (1758 m) care se desface apoi în trei culmi cuprinse între Jiu și Gilort. Din apropierea Vf. Mîndra se desface spre SV culmea cuprinsă între Vf. Țapu (2110 m) și Vf. Recii (1468 m). ',
        'Din punct de vedere geomorfologic, culmea principală a Munților Parâng poate fi împărțită în două sectoare: sectorul vestic mai înalt, marcat predominant de relief glaciar și sectorul estic cu altitudini reduse. ',
    ]
   },

   belioara1: {
    descriere: [
        'Rezervația Geo- Botanică Scărița – Belioara, Muntele Mare, jud.Alba este una dintre cele mai valoroase și reprezentative rezervații din Munții Apuseni. Aceasta cuprinde platoul calcaros Șesul Craiului, Vârful Scărița (1382m) și abrupturile spectaculoase ale obârșiilor Văii Belioara. Poteca tematică „Natura în culori”, constă în 6 panouri informative care se suprapun pe o distanță de 1,2 km. cu traseul turistic Scărița – Belioara. Informațiile de pe panouri ne ajută să știm exact unde ne aflăm și ce putem observa în zona respectivă. Eu le consider foarte utile.',
    ],
    descriere1: [
        'Drumul este în stare foarte bună, nivelat, se poate ajunge cu orice mașină. Din Poșaga de Sus se merge prin sat pe Valea Belioarei, noi am întrebat sătenii, pe lângă carieră se face un drum la dreapta. Mașinile le puteți lăsa pe marginea drumului unde este un panou cu Punctul Gastronomic local la care vă puteți reîncărca bateriile după drumeție. Atitudinea maximă se află în vârful Scărița 1384 metri. Suprafața actuală a ariei protejate este de 130 hectare. Pe suprafața ariei se regăsesc plante specifice climatelor reci alpine și subalpine (am văzut Strugurii Ursului și Gențiana Cupă) cât și plante specifice climatelor mediteraneene sau de stepă.'
    ],
    descriere2: [
        'Traseul este de tip circuit și se poate porni pe care parte doriți, stânga sau dreapta. Noi am văzut traseul filmat și am hotărât să urcăm pe partea stângă (în film pe aici coborau, ei au început drumeția pe partea dreaptă), pentru că aici există o porțiune stâncoasă abruptă pe care am considerat ca e mai simplu de urcat decât de coborât. Pe această parte avem marcaj dublu punct roșu și cruce roșie. Trebuie să treceți printr-o poartă mare de lemn după care veți urca pe o pantă abruptă cu iarbă. Urmează apoi o scurtă urcare prin pădure care vă scoate la un munte stâncos, alb, abrupt, dar chipeș, pe care trebuie să-l urcați folosindu-vă de mâini ca să vă sprijiniți de blocurile masive de calcar. După această porțiune care vă solicită fizic, urmează urcarea destul de lungă prin pădure, pe lângă un pârâiaș, la umbră și în acordul vesel al păsărilor.'
    ],
    descriere3: [
        'O poiană cu construcții arhaice din lemn vă permite să admirați frumusețea peisajului din jur. O altă traversare prin pădure vă scoate la golul alpin. Platoul calcaros pe care am ajuns este Șesul Craiului situat la peste 1350 metri altitudine și o suprafață de 47,7 ha. Priveliștile sunt din ce în ce mai frumoase. Sufletul bucuros de energia cu care se încarcă la vederea acestor peisaje, mulțumește trupului pentru efortul fizic depus pentru a ajunge acolo. Văi adânci fără apă, pereți verticali cu creste dantelate ascuțite și piscuri calcaroase izolate în forme diferite, turnuri uriașe, abrupturi stâncoase (de 750m înălțime), toate aceste forme te transformă într-un spectator fascinat de grandoarea naturii. Totul este uimitor și încerci să memorezi formele stâncilor asemuindu-le cu diverse animale, să le imortalizezi frumusețea în multe fotografii. Coborârea este la rândul ei la fel de abruptă ca și urcarea, doar că de această dată vom coborî în mare pare prin pădure. Noi am prins noroi și era alunecos, astfel că am coborât destul de încet și cu grijă. După ieșirea din pădurea arsă cu peisaj de film de groază (a fost un incendiu mare în luna aprilie 2020 care a fost stins după două zile, afectând peste 10 hectare de pădure), veți coborî printr-o poiană de unde veți putea admira noi forme stâncoase, abrupturi spectaculoase și veți observa portalul uriaș al peșterii Coșul Boului. Urmează apoi o porțiune destul de lungă cu grohotiș, după care ajungeți la punctul de unde ați plecat.'
    ]
   },

   pietreleD: {
    descriere: [
        'MUNŢII RARĂU - GIUMALĂU constituie o zonă turistică de mare importanță în cadrul Carpaților Orientali fiind unii dintre cei mai atrăgători, pitorești şi vizitați munți ai Bucovinei. Munții Rarău - Giumalău au o suprafață de circa 375 km2 iar altitudinile maxime se află în muntele Giumalău (Vârful Giumalău 1857m) și în muntele Rarău (Vârful Rarău 1651m). ',
        'În această zonă se găsesc două centre turistice de mare însemnătate - Câmpulung Moldovenesc și Vatra Dornei , ce constituie puncte de plecare pentru principalele fluxuri de turiști în diferite trasee montane în acești munți. ',
        'TRASEU - Dacă doriți să aveți parte de o aventură de o jumătate zi în acești munți, vă invit la o plimbare scurtă dar plină de adrenalină în Munții Rarău. Traseul este ușor accesibil din fața Cabanei Rarău și poate fi parcurs de oricine, cu un minim efort și echipament adecvat unui traseu pe stâncă, în special încălțări potrivite! ',
        'Acest traseu se desfășoară în circuit, în jurul Pietrelor Doamnei și durează aproximativ 2 ore în total, în care am inclus și o pauză de 30 de minute în punctul cel mai înalt. Presupune traversarea în prima parte a unei porțiuni stâncoase dar ușor accesibile, o porțiune de lanțuri, un superb loc de belvedere cu priveliște 360 de grade și spre final o plimbare relaxantă prin pădure. ',
        'Este marcat în totalitate cu cruce albastră . Marcajul este nou și ușor de urmărit. ',
        'ACCES - Din Câmpulung Moldovenesc, ieșim prin localitatea Pojorâta și vom urma Transrarăul - o șosea ce traversează masivul către localitatea Chiril, care se prezinta foarte bine, fiind asfaltată în totalitate. Din Pojorâta până la Hotel Rarău sunt 16km de serpentine strânse dar cu priveliști de poveste. ',
        'Facem prima oprire la un loc special amenajat de belvedere pentru a vedea cel mai înalt punct la care vom ajunge astăzi - Pietrele Doamnei. Undeva în spate se pot vedea și stația meteorologica și stația de televiziune de pe Vârful Rarău - cel mai înalt punct al acestui masiv - 1651m. ',
        ' Din parcarea cabanei Rarau vom pleca direct pe traseu, poteca conturându-se spre pădure. Găsim și un stâlp cu indicatoare spre mai multe trasee ce pot fi parcurse din acest loc, cât și câteva panouri informative despre întreaga zonă.  Pentru astăzi am ales Traseul tematic 1 - Povestea Muntelui care este marcat cu cruce albastră  și face un tur în zona de poveste - Pietrele Doamnei. '
    ],
    descriere1: [
       'Pietrele Doamnei - cel mai cunoscut obiectiv turistic din munții Rarău oferă un relief ruiniform alcătuit dintr-un ansamblu de turnuri din calcare mezozoice încrustate cu corali și amoniți, cu înălțimi de la sub 10 m la peste 70 m, înconjurate de o masă de grohotișuri ce au dimensiuni variabile. Ele sunt rezultate prin fragmentarea (îngheț - dezgheț) unui vârf calcaros. ',
       'Cu o formă spectaculoasă, învăluite în mister, apariția Pietrelor Doamnei este explicată de localnici prin numeroase legende. Cea mai cunoscută dintre ele are legătură cu doamna Elena, soția voievodului Petru Rareș, la fel cum și denumirea Munților Rarău ar fi fost primită de la domnitorul Moldovei, Petru Rareș. ',
       'Se spune că în vremurile tulburi ale istoriei, în 1541, în timpul celei de-a doua domnii a lui Petru Rareș, acesta a găsit în munții Rarău un loc pentru a-și pune la adăpost familia și o parte din avere. Urmăriți de hoardele de tătari, doamna Elena și fiul Ștefăniță s-au refugiat într-o peșteră unde au început să se roage, iar la un moment dat au auzit un zgomot puternic. Legenda spune că stânci mari s-au desprins și au căzut peste locul unde se află averea domnitorului, îngropându-i pe atacatori. Doamna Elena ar fi afirmat ”Aceasta este plata pentru salvarea noastră” și, de atunci, stâncile au primit denumirea de „Pietrele Doamnei”, iar comoara stă și acum ascunsă de stâncile uriașe. ',
       'Revenind la traseu, pornim din fața cabanei ușor la deal prin pădure pentru aproximativ 10 minute urmărind marcajul pe stânci sau copaci. Pădurea se deschide curând iar peisajul se schimbă în totalitate, pădurea verde fiind înlocuită de stâncării. ',
       'Continuăm traseul prin partea dreaptă, unde se vede și marcajul, în urcare ușoară printre stânci și grohotiș. Partea spectaculoasă a traseului abia a început! Nu vă lăsați descurajați la primul urcuș pentru că veți găsi cu siguranță destule puncte de sprijin în traversarea porțiunilor stâncoase, care pot părea abrupte sau dificile la prima vedere. ',
       'Lăsând pădurea în spatele nostru, panorame largi apar de după stânci. Facem câte o scurtă oprire din loc în loc pentru a ne bucura de peisaj. ',
       'Ajungem rapid în cel mai înalt punct al acestui traseu iar efortul ne este răsplătit de panoramele superbe în toate direcțiile. Ne hotărâm să facem o pauză mai lungă, nu pentru că am fi obosit dar priveliștea merită din plin! ',
       'Spre nord vedem Depresiunea Câmpulung Moldovenesc și Obcinele Bucovinei, spre est Obcina Voronețului, spre sud Munții Bistriței și Depresiunea Țara Dornelor străjuită de masivul vulcanic al Călimanului, iar spre vest Obcina Suhardului, Munții Bârgăului şi crestele alpine ale Munților Rodnei. ',
       'Coborâm prima porțiune cu lanțuri pe unde am venit până la indicator, iar apoi vom urma spre stânga poteca marcată cu cruce albastra spre Cabana Rarău pentru aproximativ 30 de minute prin pădure. '
       
    ]
   },

   footer: {
    descriere: [
        'Pentru mai multe detalii accesati linkurile de mai jos :) Si nu uita sa dai subscribe  ⬆ ',
    ],
   },
}


